### ISSUE TITLE
Update to forge?

### ISSUE THREAD

**Issue by tykeal** [datacentred/datacentred-external_facts#2]
It's been over 7 months since I submitted the changes that got merged in to support Puppet4. Can we please get a new minor point release pushed to the forge?

If you want, I'm willing to give a PR for the metadata bump.

**Comment by tykeal** [comment]
Poke?

**Comment by yankcrime** [comment]
Sorry @tykeal - this one fell through the cracks!  Version 1.1.0 which includes your fixes for PE and Puppet 4 has been released on the Forge.

**Comment by tykeal** [comment]
Thank you!
